name: Release Packages

on:
  workflow_call:
    inputs:
      packages:
        description: "List of pakckages to release"
        required: true
        type: string

jobs:
  affected:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31

      - name: Changed packages
        id: changed-workflows
        run: |
          changed_workflows=$(echo "${{ steps.changed-files.outputs.all_modified_files }}")
          echo "Changed Workflows: $changed_workflows"
          echo "::set-output name=values::$changed_workflows"
          for package in ${{ inputs.packages }}; do
            echo "this is the pack"
            echo $package
          done

