name: Release Packages

on:
  workflow_call:
    inputs:
      packages:
        description: "List of packages to release deliminated by a space"
        required: true
        type: string

jobs:
  affected:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31

      - name: Changed packages
        id: changed-workflows
        run: |
          changed_workflows=$(echo "${{ steps.changed-files.outputs.all_modified_files }}")
          echo "Changed Workflows: $changed_workflows"
          echo "::set-output name=values::$changed_workflows"
          release_packages=""
          changes_files=$(echo "${{ steps.changed-files.outputs.all_modified_files }}")
          echo "Changed files any? "
          echo " ${changes_files[*]} "
          for package in ${{ inputs.packages }}; do
            echo "current package"
            echo $package
            if [[ "${changes_files}" == *"${package}"* ]]; then
              if [ -z "$release_packages" ]
              then
                echo "\$var is empty"
                release_packages="${release_packages}${package}"
              else
                release_packages="${release_packages},${package}"
              fi
            fi
          done
          echo "Release Packages: $release_packages"
          echo "::set-output name=values::$release_packages"

