name: 'Build donet package'

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: "dotnet version to use"
        default: 6.0.x
        required: false
        type: string
      runner:
        description: "runner to use"
        default: ubuntu-latest
        required: false
        type: string
      packages_dir:
        description: "Dir where packages can be found"
        default: ./
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Chekout repo
      uses: actions/checkout@v3
    - name: Set outputs 
      id: vars
      run: | 
        project=$(echo "${GITHUB_REF#refs/*/}" | cut -d "-" -f 1)
        package_tag=$(echo "${GITHUB_REF#refs/*/}" | cut -d "v" -f 2)
        echo ::set-output name=project_dir::${{ inputs.packages_dir }}${project}
        echo ::set-output name=tag::${package_tag}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add Nuget Source
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
    - name: Build
      working-directory: ${{ steps.vars.outputs.project_dir }}
      run: |
        dotnet pack --configuration Release /p:Version=${{ steps.vars.outputs.tag }}
    - name: Publish
      working-directory: ${{ steps.vars.outputs.project_dir }}
      run: dotnet nuget push **/*.nupkg --skip-duplicate --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
