name: Release Packages

on:
  workflow_call:
    inputs:
      packages:
        description: "List of pakckages to release"
        required: true
        type: string

jobs:
  affected:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31
        with:
          files: |
            ${{ inputs.packages }}

      - name: Changed packages
        id: changed-workflows
        run: |
          changed_workflows=$(echo "${{ steps.changed-files.outputs.all_modified_files }}")
          echo "Changed Workflows: $changed_workflows"
          echo "::set-output name=values::$changed_workflows"
          #names=${{ inputs.packages }}
          #SAVEIFS=$IFS   # Save current IFS (Internal Field Separator)
          #IFS=$'\n'      # Change IFS to newline char
          #names=($names) # split the `names` string into an array by the same name
          #IFS=$SAVEIFS   # Restore original IFS
          #echo "packages"
          #echo $names

