name: Release Packages

on:
  workflow_call:
    inputs:
      packages:
        description: "List of pakckages to release"
        required: true
        type: string

jobs:
  affected:
    runs-on: ubuntu-latest
    outputs:
      changed-workflows: ${{ steps.changed-workflows.outputs.values }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-dirs
        uses: tj-actions/changed-files@v31
        with:
          files: |
            ${{ inputs.packages }}

      - name: Get changed packages that changed
        id: changed-workflows
        run: |
          echo "${{ steps.changed-dirs.outputs.all_modified_files }}"

