name: test checks

on:
  push:
    branches:
      - main

  pull_request:
    type:
      - labeled
      - unlabeled
    branches:
      - main

jobs:
  run-echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: echo run
        run: echo "hello world"

  run-with-status:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: echo run
        run: |
          echo "hello world"
          exit 0
